unitycatalog/unitycatalog

- README.md
- docs/tutorial.md
Change the cmd flag from --format to --output. Otherwise following error will raise:
```
$ bin/uc table list --catalog unity --schema default --format jsonPretty
Some of the provided parameters are not valid.
Usage: bin/uc table list [options]
Required Params:
--catalog The name of the catalog.
--schema The name of the schema.
Optional Params:
--max_results The maximum number of results to return.
```
> Change the cmd flag from --format to --output

- server/src/main/java/io/unitycatalog/server/service/IcebergRestCatalogService.java
- server/src/test/java/io/unitycatalog/server/iceberg/IcebergRestCatalogTest.java
Fixes #10 to have the right behavior of a 400 when failing.
Currently, an IllegalArgumentException for invalid namespace will be thrown which will end up surfacing as a 500 response due to https://github.com/unitycatalog/unitycatalog/blob/main/server/src/main/java/io/unitycatalog/server/exception/GlobalExceptionHandler.java#L26 treating this as an arbitrary runtime exception. Instead a Base exception with an invalid argument error code should be thrown (looking at other parts of the code, this seems to be the practice).
> Iceberg REST Service: Throw 400 if namespace is invalid

- build.sbt
Set Test Log Level to `Info` globally. Previously we were not seeing individual test information for `server`  sbt project. This global setting enables printing of the same while running tests.
**Testing**
The same can be cross-checked from the `Run tests`  steps of the `build` Workflow of this PR.
> Set Test Log Level to Info globally

- dev/checkstyle-config.xml
removed docstyle declaration to enable the checkstyle to run - this docstyle element was not present in spark and delta for example
linked issue: https://github.com/unitycatalog/unitycatalog/issues/98
checkstyle now runs and flags 1538 errors
> issue 98 - item 1 - removed doctype to allow checkstyle to run

- server/src/main/java/io/unitycatalog/server/persist/dao/CatalogInfoDAO.java
- server/src/main/java/io/unitycatalog/server/persist/dao/ColumnInfoDAO.java
- server/src/main/java/io/unitycatalog/server/persist/dao/PropertyDAO.java
- server/src/main/java/io/unitycatalog/server/persist/dao/SchemaInfoDAO.java
- server/src/main/java/io/unitycatalog/server/persist/dao/TableInfoDAO.java
- server/src/main/java/io/unitycatalog/server/persist/dao/VolumeInfoDAO.java
Resolves #92.
Removes redundant entity model persistence attributes and aligns the formatting across models.
- The default [@Column#length() is 255](https://jakarta.ee/specifications/persistence/2.2/apidocs/javax/persistence/column#length())
- The default [@OneToMany#fetch() strategy is FetchType.LAZY](https://jakarta.ee/specifications/persistence/2.2/apidocs/javax/persistence/onetomany#fetch())
> Remove redundant column properties from entity objects

- build.sbt
Resolves #91.
> Whenever build/sbt test command is run, the warnings below are printed to the console:
>    [warn] there are 3 keys that are not used by any other settings/tasks:
>    [warn]  
>    [warn] * cli / Compile / logLevel
>    [warn]   +- /home/runner/work/unitycatalog/unitycatalog/build.sbt:206
This issue comes from the [key linting](https://github.com/sbt/sbt/pull/5153) added in sbt 1.4.0, which warns keys are used by some tasks but not by others. In our case, `Compile / logLevel` is used in `cli`, `client`, `server` but not in `apiDocs`.
> Fix warnings on log level variables on running sbt test command

- server/src/test/java/io/unitycatalog/server/base/function/BaseFunctionCRUDTest.java
- server/src/test/java/io/unitycatalog/server/base/volume/BaseVolumeCRUDTest.java
- server/src/test/java/io/unitycatalog/server/iceberg/IcebergRestCatalogTest.java
- server/src/test/java/io/unitycatalog/server/sdk/tables/SdkTableCRUDTest.java
- server/src/test/java/io/unitycatalog/server/utils/FileUtilsTest.java
The `assert` keyboard in Java needs to be explicitly enabled (via `-ea`), otherwise it doesn't do anything and gets optimized away. There are also a few `assert` usages in web service code and those should be replaced either with `Preconditions.checkNotNull` or with a Validation API
> Replace assert with assertThat in tests

- server/src/main/java/io/unitycatalog/server/exception/IcebergRestExceptionHandler.java
- server/src/main/java/io/unitycatalog/server/service/IcebergRestCatalogService.java
- server/src/test/java/io/unitycatalog/server/iceberg/IcebergRestCatalogTest.java
Added a specific Iceberg REST handler for the Iceberg REST service/endpoints. This produces JSON error responses in line with Iceberg REST spec.
Also stubbed out an endpoint for loadView because the Iceberg REST client tries to load a table with given name and if table is not found, it will try to load a view with given name (so, for now, we're just returning a 404 for that endpoint).
**Related Issue**
Addresses https://github.com/unitycatalog/unitycatalog/issues/46
**Testing**
Added Iceberg REST error parsing to current tests.
> implement proper error responses for Iceberg REST endpoints

- mkdocs.yml
Trino Iceberg connector doesn't have any tests for Unity catalog and it doesn't work as far as I confirmed. 
I would recommend hiding the documentation until the connector supports the integration officially. 
Relates to https://github.com/unitycatalog/unitycatalog/issues/162
> Hide Trino integration from documentation

- build.sbt
Maybe I'm mistaken, but think we don't have to worry about test dependency licenses? (those won't be shipped)
@Fokko thoughts?
> set the licensecheck to check only compile dependencies

- connectors/spark/etc/conf/server.properties
- connectors/spark/src/main/scala/io/unitycatalog/connectors/spark/UCSingleCatalog.scala
- connectors/spark/src/test/java/io/unitycatalog/connectors/spark/SparkIntegrationTest.java
To support credential, the first step is to get credential of the managed table and put it into table scan/write operator's options, so that it will be part of the Hadoop conf that is used to do the actual file operations.
> Set managed table's credential to table scan/write operator's options

- docs/usage/cli.md
- examples/cli/src/main/java/io/unitycatalog/cli/VolumeCli.java
- examples/cli/src/main/java/io/unitycatalog/cli/utils/CliUtils.java
- examples/cli/src/test/java/io/unitycatalog/cli/volume/CliVolumeOperations.java
- server/src/main/java/io/unitycatalog/server/persist/VolumeRepository.java
- server/src/test/java/io/unitycatalog/server/base/volume/BaseVolumeCRUDTest.java
Making `update volume` work similarly to how `update catalog` was changed to work in PR #158 and `update schema`was changed to work in PR #219
Closes #110
Two main changes:
- Changed the parameter new_name to be optional in the server and CLI.
- Changed both the CLI and `VolumeRepository.updateVolume` to not update anything if no parameters are provided to update.
- CLI just prints a help message listing all optional parameters.
- `VolumeRepository.updateVolume` just returns existing `VolumeInfo`.
> update volume: changing new_name to be optional and making empty updates change nothing

- build.sbt
- docs/usage/server.md
- server/src/main/java/io/unitycatalog/server/UnityCatalogServer.java
Added checks for flags -p and --port to configure the port while starting the UC server. The default is 8080.
Usage:
```sh
bin/start-uc-server -p <port_number>
or
bin/start-uc-server --port <port_number>
```
~~The previous method of specifying the port ```bin/start-uc-server <port_number>``` will print the error message: "Invalid argument: <port_number>. Please use -p or --port to specify the port number."~~
Updated the code to utilize [Apache Commons CLI](https://commons.apache.org/proper/commons-cli/).
Fixes #250
> allow configuration for server port

- docs/usage/tables/index.md
- mkdocs.yml
This PR adds an index.md as overview page for the Tables docs.
The `toc` is a manual implementation. It will be great to have this automized using `[TOC]` at some point but I couldn't get this to work.
context: https://github.com/squidfunk/mkdocs-material/discussions/5200
> docs: add table index

- mkdocs.yml
This adds the `navigation.indexes` feature so that top-level directories in the nav bar can be clickable and point to overview pages.
Make the section header clickable by adding an `index.md` file to the directory. Also make sure to add the `index.md` to the `nav` in the `mkdocs.yml` file.
usage:
```
nav:
- Section:
- section/index.md 
- Page 1: section/page-1.md
...
- Page n: section/page-n.md
```
> docs: add clickable index feature

- connectors/spark/src/main/scala/io/unitycatalog/connectors/spark/UCSingleCatalog.scala
- connectors/spark/src/test/java/io/unitycatalog/connectors/spark/CredentialTestFileSystem.java
- connectors/spark/src/test/java/io/unitycatalog/connectors/spark/SparkIntegrationTest.java
[FOLLOW-UP] Format Spark Integration code by javafmtAll.
> [FOLLOW-UP] Format Spark Integration code by javafmtAll

- connectors/spark/src/test/java/io/unitycatalog/connectors/spark/SparkIntegrationTest.java
Test setCurrentCatalog and setCurrentDatabase. Note that we identified a Spark issue that needs a fix on Spark side to support `spark_catalog` override in UC.
> Test setCurrentCatalog and setCurrentDatabase

- dev/checkstyle-config.xml
- [x ] A description of the changes is added to the description of this PR.
- [x ] If there is a related issue, make sure it is linked to this PR.
Removed the checkstyle configuration that related to the order and line space for import statements in the java code. This was different to the order enforced by javafmt
see: https://github.com/unitycatalog/unitycatalog/issues/98
also some discussion here: https://github.com/unitycatalog/unitycatalog/pull/289
> removed checkstyle import order configuration

- connectors/spark/src/test/java/io/unitycatalog/connectors/spark/BaseSparkIntegrationTest.java
- connectors/spark/src/test/java/io/unitycatalog/connectors/spark/SchemaOperationsTest.java
- connectors/spark/src/test/java/io/unitycatalog/connectors/spark/TableReadWriteTest.java
To facilitate future expansion, we are splitting the current mixed Spark Integration tests into the following parts:
- BaseSparkIntegrationTest abstract class: This includes the basic Spark Catalog session creation, default setup, cleanup functions, and serves as the base class for all Spark integration tests.
- SchemaOperationsTest: This tests schema-related operations such as create, delete, and list.
- TableReadWriteTest: This tests table-related operations, including read/write operations.
> Refactoring Tests Related to Spark Integration

- README.md
Fixed the Docker [README.md](https://github.com/unitycatalog/unitycatalog/blob/main/docker/README.md) link present in UC QuickStart [Prerequisites](https://github.com/unitycatalog/unitycatalog?tab=readme-ov-file#prerequisites).
> Fix the broken link to the Docker README.md file

- build.sbt
- connectors/spark/src/test/java/io/unitycatalog/connectors/spark/TableReadWriteTest.java
This enables assertion checks across all tests/testing and then ignores/disables (for now) failing tests in spark integration tests due to delta.
> enable assertions across all tests

- connectors/spark/src/main/scala/io/unitycatalog/connectors/spark/UCSingleCatalog.scala
- connectors/spark/src/test/java/io/unitycatalog/connectors/spark/CredentialTestFileSystem.java
- connectors/spark/src/test/java/io/unitycatalog/connectors/spark/TableReadWriteTest.java
The credential support is implemented by setting hadoop conf for different table scans. This means we can't reuse FileSystem instance as it may mess up credentials. This PR explicit disables the cache.
> Fix credential support by disabling FileSystem cache

- connectors/spark/src/main/scala/io/unitycatalog/connectors/spark/UCSingleCatalog.scala
CreateTable should return from loadTable for Spark 3.5. We cannot return null until Spark 4.0
> [SPARK] CreateTable should return from loadTable for Spark 3.5

- docs/usage/functions.md
This fixes a trailing sentence in the functions docs.
> docs: fix typo

- build.sbt
This changes the Java language version to 11 for the Clients module and the Spark Connector. See Issue https://github.com/unitycatalog/unitycatalog/issues/351
> Downgrade the clients and Spark connector to Java 11 for better Spark compatibility

- docs/integrations/unity-catalog-puppygraph.md
- Documentation change only
- Add a page for integration of  Unity Catalog and PuppyGraph
> Docs: Add a PuppyGraph Integration Guide

- build.sbt
Introduce two `javacRelease` lazy vals so it's easier to track their usage. Move it up the build config file for greater visibility, as only two modules require Java 11, whereas the others are on Java 17.
This is a follow-up to https://github.com/unitycatalog/unitycatalog/pull/352
> [BUILD] Introduce javacRelease lazy vals in build config

- README.md
With this change, it's copy-and-paste away to have a fully working UC built locally and ready for local execution.
Fixes https://github.com/unitycatalog/unitycatalog/issues/362
> [DOCS] Add Building Unity Catalog section to README

- README.md
- docs/integrations/unity-catalog-spiceai.md
The Spice OSS project supports UC through unitycatalog-rs: https://github.com/spiceai/spiceai/pull/1878.
For more info  see https://docs.spiceai.org/components/catalogs/unity-catalog.
> Add Spice AI to ecosystem

- api/all.yaml
- server/src/main/java/io/unitycatalog/server/persist/TableRepository.java
Update the create table API spec to clarify only external table creation is supported. The `createTable` method in `TableRepository` already ensures only external tables are created.
> Update the create table API spec to clarify only external table creation is supported

- build.sbt
- connectors/spark/etc/conf/server.properties
- connectors/spark/src/main/scala/io/unitycatalog/connectors/spark/GcsVendedTokenProvider.java
- connectors/spark/src/main/scala/io/unitycatalog/connectors/spark/UCSingleCatalog.scala
- connectors/spark/src/test/java/io/unitycatalog/connectors/spark/BaseSparkIntegrationTest.java
- connectors/spark/src/test/java/io/unitycatalog/connectors/spark/CredentialTestFileSystem.java
- connectors/spark/src/test/java/io/unitycatalog/connectors/spark/GCSCredentialTestFileSystem.java
- connectors/spark/src/test/java/io/unitycatalog/connectors/spark/S3CredentialTestFileSystem.java
- connectors/spark/src/test/java/io/unitycatalog/connectors/spark/TableReadWriteTest.java
- server/src/main/java/io/unitycatalog/server/persist/utils/FileUtils.java
- server/src/main/java/io/unitycatalog/server/service/credential/gcp/GcpCredentialVendor.java
Updates the spark connector to support vended credentials for google cloud storage buckets.  
We use the `com.google.cloud.hadoop.util.AccessTokenProvider` interface to pass the vended credential properties stored in the hadoop conf -- see [google's gcs-connector documentation](https://github.com/GoogleCloudDataproc/hadoop-connectors/blob/7257fb4de55d83f14d4820fe00672b732d959987/gcs/CONFIGURATION.md#authentication) for more details. 
Example spark conf (assumes that the [gcs connector jar](https://github.com/GoogleCloudDataproc/hadoop-connectors/releases/download/v3.0.2/gcs-connector-3.0.2-shaded.jar) is included in the spark jars/packages as well):
```
spark.hadoop.fs.AbstractFileSystem.gs.impl 	com.google.cloud.hadoop.fs.gcs.GoogleHadoopFS …
```
> [SPARK] Support gcs reads using vended credentials

- server/src/main/java/io/unitycatalog/server/service/credential/gcp/GcpCredentialVendor.java
UC Spark Connector uses hadoop fs which does bucket/directory listings. This adds a condition to the credential access boundary in the GCS cred downscoping to allow listing objects on the prefix that is the table path.
> add condition for listing objects in gcs cred downscoping

- server/src/main/java/io/unitycatalog/server/service/credential/azure/AzureCredentialVendor.java
Azure Hadoop FS strips trailing slash when performing operations, so in order to make that work we need to vend a credential for the table path without a trailing slash.
> strip trailing slash from downscoped path for Azure vended credential

- docs/usage/tables/avro.md
This adds a docs page for creating Avro tables. Closes #205
> docs: add docs for creating Avro tables

- examples/cli/src/test/java/io/unitycatalog/cli/auth/CliAuthCrudTest.java
- server/src/main/java/io/unitycatalog/server/UnityCatalogServer.java
- server/src/main/java/io/unitycatalog/server/service/AuthService.java
- server/src/main/java/io/unitycatalog/server/service/Scim2UserService.java
Add some checking in currentUser() for the token before accessing it.
The `/self` endpoint relies on the acess-token JWT being in the request context. In order to do that, it needs to be intercepted by the `AuthDecorator` first, so adding that to the request pipeline, excluding `auth/tokens` which should be open.
Also made some changes to `/self` to make sure it found the token before trying to access it.
And the token exchange verifies the incoming token subject is in the user database.
Issue https://github.com/unitycatalog/unitycatalog/issues/429
> Fix the `/self` endpoint.

- Dockerfile
- docker/README.md
- docker/bin/build-uc-cli-docker
- docker/bin/build-uc-server-docker
- docker/bin/start-uc-server-docker
- docker/copy_jars_from_classpath.sh
- uc-cli.dockerfile
This PR changes how the UC server docker image is built (uses the faster `sbt server/package`) and copies the jars required to start it (to `jars` directory).
After https://github.com/unitycatalog/unitycatalog/commit/4b7aaa319bfad76dde4d30c9fdd5128895bf98d1, I thought I'd work on changes that would make the behaviour of the UC server when started consistent regardless whether it's in or outside Docker container (namely the welcome message at the start and no warnings).
A Dockerized UC runs in the foreground and containers are removed once stopped.
> [DOCKER] UC server container displays welcome message

- connectors/spark/src/main/scala/io/unitycatalog/connectors/spark/UCSingleCatalog.scala
at this time, we don't know if the table will be read or written. For now we always equest READ credentials as the server doesn't distinguish between READ and READ_WRITE credentials as of today. When loading a table, Spark should tell if it's for read or write, we can request the proper credential after fixing Spark.
> [SPARK] Workaround for read_write credential

- .github/workflows/publish-swagger-docs.yml
By default, the `GITHUB_TOKEN` used in GitHub Actions has read-only access to the repository. However, publishing to GitHub Pages requires write permissions to create and update the `gh-pages` branch.
This PR addresses the permission issue by explicitly granting the necessary write permissions to the GitHub Actions workflow.
Changes Made
- Added `permissions` configuration to the workflow file
- Specified `contents: write`  and `pages: write`  to allow modification of repository contents
- This change enables the creation and updating of the `gh-pages` branch
> Permission  for GH token to publish swagger GH pages

- build.sbt
Fixing the build.sbt file to generate the controlApi jar. 
This PR modifies the .root aggregate method in the build.sbt file to enable the generation of additional JAR files. These changes were necessary because `build/sbt clean package publishLocal spark/publishLocal` command which was used to generate the spark connector jar had a dependency on the controlAPi jar.
> Fixing build.sbt to generate controlApi jar 

- build.sbt
- connectors/spark/src/main/scala/io/unitycatalog/connectors/spark/UCSingleCatalog.scala
- connectors/spark/src/test/java/io/unitycatalog/connectors/spark/TableReadWriteTest.java
Use the Delta 3.2.1 RC so that these ignored Delta tests can be enabled. Also fixes the gs/abfs credential support in the Delta tests, by disabling the file system cache, the same as we did for s3.
> enable Delta tests and fix gs/abfs credential

- docs/integrations/unity-catalog-daft.md
Updates the documentation around integration with Daft so that the guide can be followed without running into errors.
- `daft.read_delta_lake` does not exist, the right API is `daft.read_deltalake` (see the related Daft docs [here](https://www.getdaft.io/projects/docs/en/latest/api_docs/doc_gen/io_functions/daft.read_deltalake.html#daft.read_deltalake))
- Daft must be installed including extras `unity` and `deltalake`, otherwise `daft.read_deltalake` will raise `ModuleNotFoundError`
> docs: fix Daft integration guide

- server/src/main/java/io/unitycatalog/server/UnityCatalogServer.java
- server/src/main/java/io/unitycatalog/server/auth/decorator/KeyMapperUtil.java
- server/src/main/java/io/unitycatalog/server/auth/decorator/UnityAccessDecorator.java
- server/src/main/java/io/unitycatalog/server/persist/TableRepository.java
- server/src/main/java/io/unitycatalog/server/persist/VolumeRepository.java
- server/src/main/java/io/unitycatalog/server/service/TemporaryModelVersionCredentialsService.java
- server/src/main/java/io/unitycatalog/server/service/TemporaryPathCredentialsService.java
- server/src/main/java/io/unitycatalog/server/service/TemporaryTableCredentialsService.java
- server/src/main/java/io/unitycatalog/server/service/TemporaryVolumeCredentialsService.java
This is a follow on to the overall access control feature to add access control to the credential vending endpoints. The access control rules for credential vending follows the same rules as getting the entity.
This resolve Issue https://github.com/unitycatalog/unitycatalog/issues/501
> Add access control to temporary credentials endpoints.

- api/Models/UpdateModelVersion.md
- api/Models/UpdateRegisteredModel.md
- api/all.yaml
- examples/cli/src/main/java/io/unitycatalog/cli/ModelCli.java
- examples/cli/src/main/java/io/unitycatalog/cli/ModelVersionCli.java
- examples/cli/src/test/java/io/unitycatalog/cli/model/CliModelOperations.java
- server/src/main/java/io/unitycatalog/server/persist/ModelRepository.java
- server/src/main/java/io/unitycatalog/server/service/ModelService.java
- server/src/test/java/io/unitycatalog/server/base/model/BaseModelCRUDTest.java
Fix a bug where the path variables for UpdateModelVersion and UpdateRegisteredModel were being ignored in favor of the incorrectly added variables in the request object.
- Request object has been fixed
- Path variables are passed in correctly for both handlers and used
- All existing code that relied on extraneous fields in generated code has been fixed
- All tests continue to pass
> Fix UpdateRegisteredModel and UpdateModelVersion to honor path variables

- server/src/main/java/io/unitycatalog/server/UnityCatalogServer.java
- server/src/main/java/io/unitycatalog/server/auth/UnityCatalogAuthorizer.java
- server/src/main/java/io/unitycatalog/server/service/PermissionService.java
This is a follow-up to f9a9bf1f84cb4c7fa03ecb569ae19f306a7cd85b:
1. Removes a code duplication
2. `@Get("/function/{name}")`
3. Removes `public` qualifiers in `UnityCatalogAuthorizer` interface
/cc @creechy
> [MINOR] Remove duplicate + no publics in interface

- build.sbt
This change makes sure that there is one version of Delta Lake (based on a lazy val shared across subprojects).
> Use one version of Delta Lake consistently

- server/src/main/java/io/unitycatalog/server/UnityCatalogServer.java
- server/src/main/java/io/unitycatalog/server/persist/utils/FileUtils.java
- server/src/main/java/io/unitycatalog/server/persist/utils/HibernateUtils.java
- server/src/main/java/io/unitycatalog/server/persist/utils/UriUtils.java
- server/src/main/java/io/unitycatalog/server/service/AuthService.java
- server/src/main/java/io/unitycatalog/server/service/Scim2UserService.java
- server/src/main/java/io/unitycatalog/server/service/credential/aws/AwsCredentialVendor.java
- server/src/main/java/io/unitycatalog/server/service/credential/aws/S3StorageConfig.java
- server/src/main/java/io/unitycatalog/server/service/credential/azure/AzureCredentialVendor.java
- server/src/main/java/io/unitycatalog/server/service/credential/gcp/GcpCredentialVendor.java
- server/src/main/java/io/unitycatalog/server/service/iceberg/FileIOFactory.java
- server/src/main/java/io/unitycatalog/server/service/iceberg/TableConfigService.java
- server/src/main/java/io/unitycatalog/server/utils/ServerProperties.java
- server/src/test/java/io/unitycatalog/server/service/credential/CredentialOperationsTest.java
As agreed with @alexreid-db, `ServerPropertiesUtils` should really be in `io.unitycatalog.server.utils` package.
The other changes are mainly as follows:
1. No need for `Utils` suffix
2. Added `isAuthorizationEnabled` method
3. Javadoc
> Refactor ServerPropertiesUtils (to be ServerProperties)

- server/src/main/java/io/unitycatalog/server/UnityCatalogServer.java
- server/src/main/java/io/unitycatalog/server/utils/OptionParser.java
- server/src/test/java/io/unitycatalog/server/utils/OptionParserTest.java
This PR adds `h/help` option for `bin/start-uc-server` to print the usage guide
```
bin/start-uc-server -v
0.2.0-SNAPSHOT
bin/start-uc-server -h
usage: bin/start-uc-server
-h,--help         Print help message.
-p,--port <arg>   Port number to run the server on. Default is 8080.
-v,--version      Display the version of the Unity Catalog server
```
> Add h/help option for unity catalog server

- docs/integrations/unity-catalog-puppygraph.md
Fix the broken link in the docs pointing to the Spark Integration instead of the Spark Connector in the PuppyGraph integration documentation page.
Resolves #564
> Fix broken link to Spark Connector in PuppyGraph integration

- server/src/main/java/io/unitycatalog/server/persist/ModelRepository.java
https://github.com/unitycatalog/unitycatalog/pull/595 added javafmtCheck, but the `ModelRepository.java` file submitted by 
https://github.com/unitycatalog/unitycatalog/pull/590 was not formatted, which resulted in a GA check error. 
- https://github.com/unitycatalog/unitycatalog/actions/runs/11300626359/job/31433764692
```
[warn] server/src/main/java/io/unitycatalog/server/persist/ModelRepository.java isn't formatted properly!
[error] 1 file must be formatted
[error] (server / Compile / javafmtCheck) 1 file must be formatted
[error] Total time: 5 s, completed Oct 12, 2024, 8:11:48 AM
```
This pr used `build/sbt javafmt` to format the `ModelRepository.java` file in order to fix the GA(javafmtCheck) issue.
> Reformat `ModelRepository.java` to pass javafmtCheck

- .gitignore
- build.sbt
- docs/integrations/unity-catalog-puppygraph.md
- integration-tests/README.md
- integration-tests/etc/conf/server.properties
- integration-tests/src/test/java/io/unitycatalog/integrationtests/BaseSparkTest.java
- integration-tests/src/test/java/io/unitycatalog/integrationtests/SparkDeltaTableCRUDTest.java
- integration-tests/src/test/java/io/unitycatalog/integrationtests/SparkParquetTableCRUDTest.java
Adds spark integration tests that a user can manually run to test basic spark functionality against local FS and against S3/GCP/Azure cloud buckets.
Out of scope and/or Followup items:
- It'd be nice to add a dimension for testing multiple catalog endpoints as well (or at least parameterize so that different catalog conf could be used for different clouds)
- Shared/ project specific cloud resources (this will require provisioning buckets / secrets management for this project specifically)
- Github actions automation
> Spark integration tests against cloud resources

- unitycatalog-ai/src/ucai/core/databricks.py
- unitycatalog-ai/src/ucai/core/envs/databricks_env_vars.py
- unitycatalog-ai/tests/core/databricks/test_databricks_unit_tests.py
This PR adds client-based retry for temporary auth credentials expiry to the DatabricksFunctionClient.
> Add client retry logic for Databricks Unity Catalog AI Client

- ai/core/src/unitycatalog/ai/core/utils/function_processing_utils.py
- ai/core/tests/core/databricks/test_databricks_integration_tests.py
- ai/integrations/langchain/tests/test_langchain_toolkit.py
With the latest langchain version, if the UC function has no params then the schema is not correctly parsed. We should use `create_model` instead of `BaseModel`, added test for this.
Test validation: https://github.com/databricks-eng/ai-oss-integration-tests-runner/actions/runs/11567043081/job/32198004224
> Fix UC function schema when no params are needed

- ai/integrations/langchain/src/unitycatalog/ai/langchain/toolkit.py
- ai/integrations/langchain/tests/test_langchain_toolkit.py
- ai/integrations/llama_index/src/unitycatalog/ai/llama_index/toolkit.py
- ai/integrations/llama_index/tests/test_llama_index_toolkit.py
For these tools, we convert the original uc function name `catalog.schema.function` to `catalog__schema__function` (max length 64) to be compatible with OpenAI requirements, but sometimes we need to extract the original uc function name in the downstream usages. So saving the original uc function name directly to avoid any conversion error.
> Add uc_function_name to tools

- ai/core/src/unitycatalog/ai/test_utils/client_utils.py
- ai/core/tests/core/databricks/test_databricks_integration_tests.py
Randomly, some of our e2e tests failed due to what seems to be a service race condition on our workspace between creating a function and immediately executing it. Since on subsequent tests, random tests failed with different issues (most related to either overwriting a function that didn't show as existing yet or failing to execute a function that had just been created), it makes sense to introduce some retry logic so that we don't get alarm exhaustion for these e2e tests.
> Fix intermittent flaky tests for e2e suites

- ai/core/src/unitycatalog/ai/core/databricks.py
- ai/core/src/unitycatalog/ai/core/utils/function_processing_utils.py
- ai/core/tests/core/databricks/test_databricks_integration_tests.py
- ai/core/tests/core/databricks/test_databricks_unit_tests.py
- ai/core/tests/core/test_utils.py
This change adjusts the SQL sanitization logic for string input parameters (arguments) to UC function calls to only apply locally in order to prevent valid SQL string command objects that are wrapped in single quotes from being converted to double-single-quote wrapping, which is invalid as a SQL statement.
> Adjust parameter input sanitization to only apply locally to strings

- docs/usage/tables/formats.md
- docs/usage/tables/uniform.md
Update the formatting of the `usage/tables` documentation pages by using markdownlint. User-facing changes have been kept minimal.
Resolves #675
> Formate usage/tables documentation pages via markdownlint

- docs/usage/cli.md
- docs/usage/functions.md
- docs/usage/models.md
- docs/usage/ui.md
- docs/usage/volumes.md
Update the formatting of the `usage` documentation pages by using markdownlint. User-facing changes have been kept minimal.
Resolves #682
> Formate usage documentation pages via markdownlint

- ai/core/src/unitycatalog/ai/core/databricks.py
- ai/core/src/unitycatalog/ai/core/utils/function_processing_utils.py
- ai/core/src/unitycatalog/ai/test_utils/function_utils.py
- ai/core/tests/core/databricks/test_databricks_integration_tests.py
- ai/core/tests/core/databricks/test_databricks_unit_tests.py
- ai/core/tests/core/test_utils.py
Update the logic of serverless execution to pass arguments using `:` prefix by SQL literals. Wrap the exception to provide better error message when failing. 
Drop the previous sanitization logic as we no longer need it :) SQL side can deal with the single+double quotes combination correctly.
Updated tests.
> Fix execute_function string parsing with serverless

- build.sbt
Currently, there are no release settings configured for the python client which cause the `build/sbt release` command to fail. Skipping python client release in maven since there needs to be a separate flow to publish to pypi
> skip maven release for python client

- connectors/spark/src/test/java/io/unitycatalog/spark/BaseSparkIntegrationTest.java
- connectors/spark/src/test/java/io/unitycatalog/spark/TableReadWriteTest.java
- docs/usage/tables/uniform.md
- server/src/main/java/io/unitycatalog/server/exception/IcebergRestExceptionHandler.java
- server/src/main/java/io/unitycatalog/server/service/IcebergRestCatalogService.java
- server/src/test/java/io/unitycatalog/server/service/IcebergRestCatalogTest.java
Prior to this PR, users were required to lookup namespace and tables by supplying the uc catalog name in the namespace identifier which isn't proper and lead to problems. This PR implements the REST client flow of configuring calls to the API with a defined prefix containing the catalog name. The catalog name is now part of the API paths and broken apart from the namespace.
Client (passes warehouse parameter) -> Server Config Endpoint (response has override for URL prefix) -> Client
Subsequent calls to the API now has url prefixed with `/catalogs/{warehouse/catalog-name}`
This PR "binds" the spark catalog to a UC catalog using the client config endpoint. Users must now add to their catalog configurations something like (example in spark): …
> handle catalog and namespace properly in Iceberg REST api

- docs/integrations/unity-catalog-trino.md
- mkdocs.yml
This PR adds the trino docs back to the integration section
Signed-off-by: Avril Aysha <68642378+avriiil@users.noreply.github.com>
> docs: add trino docs back

- ai/core/src/unitycatalog/ai/core/databricks.py
If the client is run on non-serverless computes, we should warn the user as some of the functionalities might not work well. 
Non-dbconnect sparkSession doesn't contain `is_stopped` attribute.
After this PR:
Also updated the exception catch in serverless to include result part, as the calculation happens when collect is called.
https://github.com/databricks-eng/ai-oss-integration-tests-runner/actions/runs/11813567109 passed
> Fix client execution issue for SparkSession references

- connectors/spark/src/test/java/io/unitycatalog/spark/BaseSparkIntegrationTest.java
- connectors/spark/src/test/java/io/unitycatalog/spark/TableReadWriteTest.java
- docs/usage/tables/uniform.md
- server/src/main/java/io/unitycatalog/server/exception/IcebergRestExceptionHandler.java
- server/src/main/java/io/unitycatalog/server/service/IcebergRestCatalogService.java
- server/src/test/java/io/unitycatalog/server/service/IcebergRestCatalogTest.java
Prior to this PR, users were required to lookup namespace and tables by supplying the uc catalog name in the namespace identifier which isn't proper and lead to problems. This PR implements the REST client flow of configuring calls to the API with a defined prefix containing the catalog name. The catalog name is now part of the API paths and broken apart from the namespace.
Client (passes warehouse parameter) -> Server Config Endpoint (response has override for URL prefix) -> Client
Subsequent calls to the API now has url prefixed with `/catalogs/{warehouse/catalog-name}`
This PR "binds" the spark catalog to a UC catalog using the client config endpoint. Users must now add to their catalog configurations something like (example in spark): …
> [0.2] handle catalog and namespace properly in Iceberg REST api (#324)

- server/src/main/java/io/unitycatalog/server/security/SecurityContext.java
- server/src/main/java/io/unitycatalog/server/service/AuthDecorator.java
- server/src/main/java/io/unitycatalog/server/service/AuthService.java
- server/src/main/java/io/unitycatalog/server/utils/JwksOperations.java
Fixes https://github.com/unitycatalog/unitycatalog/issues/730 and adds the following:
1. Uses built-in claim names (`JwtClaim.EMAIL`, `JwtClaim.SUBJECT`)
1. Uses built-in claim accessors (`decodedJWT.getIssuer()`, `decodedJWT.getKeyId()`, `decodedJWT.getSubject()`)
1. More DEBUG logging in OAuth2 execution paths
> Accept http URLs in OAuth2 Token Exchange

- server/src/main/java/io/unitycatalog/server/service/AuthService.java
- server/src/test/java/io/unitycatalog/server/service/AuthServiceTest.java
Logout endpoint was implemented to expire cookie as part of the task https://github.com/unitycatalog/unitycatalog/pull/593 and changes are pushed as part of PR https://github.com/unitycatalog/unitycatalog/pull/678 but when the endpoint was called it gets hung indefinitely , On further investigation non empty data needs to be send as part of the header when we expire the cookie. This PR has the fix for the same.
> Send non empty data as part of expired cookie in the header

- build.sbt
Run `build/sbt -J-Xmx2G test`, we can see 3 times(when test `unitiycatalog-server`, `unitiycatalog-cli`and  `unitiycatalog-spark`) logs similar to the following:
```
[error] SLF4J(W): Class path contains multiple SLF4J providers.
[error] SLF4J(W): Found provider [org.apache.logging.slf4j.SLF4JServiceProvider@7d952499]
[error] SLF4J(W): Found provider [org.slf4j.reload4j.Reload4jServiceProvider@62592f6d]
[error] SLF4J(W): See https://www.slf4j.org/codes.html#multiple_bindings for an explanation.
[error] SLF4J(I): Actual provider is of type [org.apache.logging.slf4j.SLF4JServiceProvider@7d952499]
```
We can also see it in GA test logs, for example:
- https://github.com/unitycatalog/unitycatalog/actions/runs/11473447061/job/31927701381
So this pr …
> Globally exclude `org.slf4j:slf4j-reload4j`

- server/src/main/java/io/unitycatalog/server/persist/dao/FunctionInfoDAO.java
This change allows for realistic python callable descriptions (`comment`) and function bodies (`routine_definition`) to be written to the UC server. Otherwise, the default of maximum 255 characters is not sufficient for any meaningful use of this service for real-world python functions.
> Patch FunctionInfo to support python callables

- server/src/main/java/io/unitycatalog/server/persist/dao/FunctionInfoDAO.java
By the default definitions, these field definitions that are used for functions definitions all have a limit at 255 characters. This is insufficient for most 'real-world' python functions and will impact the capabilities for ai function calling (the `routineDefinition` is a hard blocker; and the `comment` field will impact the usefulness of a defined and configured GenAI tool that is utilizing a UC function). 
The changes to these fields will enable full usage for the AI integrations.
> Update field sizes to support Python Functions usage

- docs/integrations/unity-catalog-spark.md
This fix clarifies catalog naming inside the Spark configs.
Signed-off-by: Avril Aysha <68642378+avriiil@users.noreply.github.com>
> [DOCS] clarify catalog naming in Spark configs

- build.sbt
This is an upgrade to the log4j version, from 2.23.1 to 2.24.3. The current version has a vulnerability which results in `sbt` not downloading the artifact, causing new builds to fail, unless those artifacts had previously been cached locally.
See Issue https://github.com/unitycatalog/unitycatalog/issues/879
> Update log4j version due to vulnerability with 2.23.1 and build failure.

- ui/src/components/layouts/DetailsLayout.tsx
- ui/src/utils/getChildOnType.ts
While displayName works in dev, it gets minified for production builds. What this means is that no children are matched to the displayName so nothing is actually rendered.
Matching on the actual type works both in dev and prod builds.
> Bugfix: Fix getting child element on UI

- ai/core/README.md
- ai/core/src/unitycatalog/ai/core/client.py
- ai/core/src/unitycatalog/ai/core/databricks.py
- ai/core/src/unitycatalog/ai/core/utils/function_processing_utils.py
- ai/core/src/unitycatalog/ai/core/utils/type_utils.py
- ai/core/tests/core/databricks/test_databricks_integration_tests.py
- ai/core/tests/core/databricks/test_databricks_unit_tests.py
- ai/core/tests/core/oss/test_oss_client.py
- docs/ai/client.md
Fixes an issue with default parameter value handling where the parameters were not reading in the defaults from the FunctionInfo configuration properly.
> Add parameter default handling correction for UnityCatalog AI clients

- compose.yaml
Updates the docker compose configuration to pull the [latest official image](https://hub.docker.com/repository/docker/unitycatalog/unitycatalog/general) from DockerHub, rather than have the user build the image locally from `main`.
> Add UC latest official image to compose.yaml 

- ai/core/README.md
- ai/core/src/unitycatalog/ai/core/base.py
- ai/core/src/unitycatalog/ai/core/client.py
- ai/core/src/unitycatalog/ai/core/databricks.py
- ai/core/src/unitycatalog/ai/core/utils/callable_utils.py
- ai/core/src/unitycatalog/ai/core/utils/execution_utils.py
- ai/core/src/unitycatalog/ai/core/utils/type_utils.py
- ai/core/tests/core/databricks/test_databricks_integration_tests.py
- ai/core/tests/core/databricks/test_databricks_unit_tests.py
- ai/core/tests/core/oss/test_oss_client.py
- ai/core/tests/core/test_callable_utils.py
- ai/core/tests/core/test_client.py
- ai/core/tests/core/test_execution_utils.py
- docs/ai/client.md
Extension of #911 , bringing a unified functionality across both clients. Adds a utility for converting the string representation to an actual callable for local execution.
> Add functionality for retrieving callable definitions and converting them to callables

- .github/workflows/ucai-core-tests.yml
- ai/core/src/unitycatalog/ai/core/databricks.py
- ai/core/src/unitycatalog/ai/test_utils/client_utils.py
- ai/core/tests/core/databricks/test_databricks_unit_tests.py
This PR forces the SparkSession (triggered by the call to `set_default_spark_session` and the call to the builder to reconnect to the serverless instance in the case of session or cluster invalidation) to rebuild the spark session in accordance with recommendations of the serverless team. Also, in the event that the retry logic is exhausted, provide guidance for notebook users on how they can quickly get back up and running by detaching and reattaching their notebook to an active serverless cluster instance.
> Fix serverless session resumption

- ai/integrations/anthropic/tests/test_anthropic_utils.py
- ai/integrations/openai/tests/test_openai_utils.py
After merging both the dbconnect pin restriction AND the serverless retry logic, it turns out that we need another patch for the spark session initialization in the utils patch fixtures.
> Fix Anthropic and OpenAI utils tests

- ai/core/src/unitycatalog/ai/core/databricks.py
- ai/core/src/unitycatalog/ai/test_utils/client_utils.py
- ai/core/tests/core/databricks/test_databricks_integration_tests.py
In this PR, if a client is defined, the config is propagated to the Databricks Session. This is done by setting the `sdkConfig` parameter. However this parameter cannot be set when serverless is set to True. So we first alter the config and set serverless to auto, which has the same effect as setting `serverless` to True on Databricks Session.
> Propagate Workspace Client Config to DB Connect

- ai/core/src/unitycatalog/ai/core/databricks.py
- ai/core/src/unitycatalog/ai/core/utils/function_processing_utils.py
- ai/integrations/anthropic/src/unitycatalog/ai/anthropic/toolkit.py
- ai/integrations/anthropic/tests/test_anthropic_toolkit.py
- ai/integrations/autogen/src/unitycatalog/ai/autogen/toolkit.py
- ai/integrations/autogen/tests/test_autogen_toolkit.py
- ai/integrations/crewai/src/unitycatalog/ai/crewai/toolkit.py
- ai/integrations/crewai/tests/test_crewai_toolkit.py
- ai/integrations/gemini/src/unitycatalog/ai/gemini/toolkit.py
- ai/integrations/gemini/tests/test_gemini_toolkit.py
- ai/integrations/langchain/src/unitycatalog/ai/langchain/toolkit.py
- ai/integrations/langchain/tests/test_langchain_toolkit.py
- ai/integrations/litellm/src/unitycatalog/ai/litellm/toolkit.py
- ai/integrations/litellm/tests/test_litellm_toolkit.py
- ai/integrations/llama_index/src/unitycatalog/ai/llama_index/toolkit.py
- ai/integrations/llama_index/tests/test_llama_index_toolkit.py
- ai/integrations/openai/src/unitycatalog/ai/openai/toolkit.py
- ai/integrations/openai/tests/test_openai_toolkit.py
This pr introduces a new flag `filter_accessible_functions` to UCFunctionToolkit. When set to true and a client's get function throws a permission error, this function is skipped when adding to UCFunctionToolkit
> Uc function client invoker access

- docs/ai/integrations/langchain.md
When testing the LangChain integration code I ran into the following error when creating the Toolkit instance following the syntax in the docs:
`UC function client is not set.`
Adding the `client=client` to define the UC function client solves the issue. Feedback welcome.
> [DOCS] add client definition to toolkit creation

- ai/core/pyproject.toml
We shouldn't be including the old asyncio dependency in the build as it is incompatible with Python 3.13. The functionality of this library was merged many years ago into the core asyncio built-in provided asyncio module within base Python.
> Remove ancient package dependency

- ai/core/src/unitycatalog/ai/core/base.py
- ai/core/src/unitycatalog/ai/core/utils/client_utils.py
- ai/integrations/anthropic/tests/test_anthropic_toolkit_oss.py
- ai/integrations/anthropic/tests/test_anthropic_utils.py
- ai/integrations/autogen/tests/test_autogen_toolkit_oss.py
- ai/integrations/crewai/tests/test_crewai_toolkit_oss.py
- ai/integrations/gemini/tests/test_gemini_toolkit_oss.py
- ai/integrations/langchain/tests/test_langchain_toolkit_oss.py
- ai/integrations/litellm/tests/test_litellm_toolkit_oss.py
- ai/integrations/litellm/tests/test_litellm_utils.py
- ai/integrations/llama_index/tests/test_llama_index_toolkit_oss.py
- ai/integrations/openai/tests/test_openai_toolkit_oss.py
We don't need a warning for get_uc_function_client when it's none. It's also confusing when it's used in validate_or_set_default_client.
This PR also moves the logic to set default client in get_uc_function_client, so users don't need to create a UCFunctionToolkit in order to trigger default client setup.
> Set default client in get_uc_function_client

- .github/workflows/docker-build.yml
Fixes the `docker-build.yml` GitHub workflow to only login to DockerHub on `push` with tags, ie. a release by a maintainer. Previously was failing because repository secrets are not available in PRs from forks. Also uses Github Actions cache for image builds, because DockerHub would require login.
> fix: only login to docker hub on tag push

- ai/core/src/unitycatalog/ai/core/databricks.py
- ai/core/tests/core/databricks/test_databricks_unit_tests.py
Adds an info statement to make the retry and subsequent success for a terminated serverless endpoint more clear and less ambiguous of the behavior of the refresh logic.
> Add notification for users that reconnection to a serverless endpoint was successful in Unity Catalog AI client

- ai/core/src/unitycatalog/ai/core/client.py
- ai/core/src/unitycatalog/ai/core/databricks.py
- ai/core/src/unitycatalog/ai/core/utils/function_processing_utils.py
- ai/core/src/unitycatalog/ai/core/utils/pydantic_utils.py
- ai/core/src/unitycatalog/ai/core/utils/type_utils.py
- ai/core/tests/core/databricks/test_databricks_integration_tests.py
- ai/core/tests/core/oss/test_oss_client.py
- ai/core/tests/core/test_client.py
- ai/core/tests/core/test_pydantic_utils.py
- ai/core/tests/core/test_utils.py
Currently, functions that have parameter defaults with SQL "NULL" as the default value fail validation checks with a very difficult to troubleshoot error message from pydantic validators. 
This PR introduces the fix for SQL Null handling and establishes an error handler to make it easier to understand why a Validator error happens. 
However, the larger-scale wrapping of validator checks elsewhere in the code base would make a full replacement be many thousands of lines long, so will leave usage of the decorator and the function handler to later PRs.
> Unity Catalog AI client handling of SQL NULL default parameters

- connectors/spark/src/main/scala/io/unitycatalog/spark/UCSingleCatalog.scala
- connectors/spark/src/test/java/io/unitycatalog/spark/TableReadWriteTest.java
[UCSingleCatalog](https://github.com/unitycatalog/unitycatalog/blob/b141f19665c0c88ed6b72a04149881690ac29dcd/connectors/spark/src/main/scala/io/unitycatalog/spark/UCSingleCatalog.scala) is missing overloads for `loadTable` with time-travel arguments (version/timestamp). This effectively prevents time-travelling on Spark + Delta tables using SQL - Scala/python are working without this because delta-spark resolves the table itself in that case without delegating to Spark.
Note: this change doesn't add similar overloads to [UCProxy](https://github.com/unitycatalog/unitycatalog/blob/b141f19665c0c88ed6b72a04149881690ac29dcd/connectors/spark/src/main/scala/io/unitycatalog/spark/UCSingleCatalog.scala#L205C15-L205C22), so time-travel likely still won't work when a …
> Fix time-travel on Delta tables using SQL

- README.md
`spark/publishLocal` is not required to build Spark integration
> docs: spark/publishLocal is not required to build Spark integration

- ai/core/pyproject.toml
See title - sets a maximum version of `databricks-connect` for Databricks UC AI integrations, since the newest 16.4 release doesn't support serverless. In general, we can bump this maximum version when serverless support is released per https://docs.databricks.com/aws/en/dev-tools/databricks-connect/python/install#version-support-matrix. databricks-connect is forward-compatible, so using old databricks-connect on new DBR versions is expected to work fine
> [AI client] Set maximum version of databricks-connect for Databricks integration

- ai/core/src/unitycatalog/ai/core/databricks.py
- ai/core/tests/core/databricks/test_databricks_integration_tests.py
- ai/core/tests/core/databricks/test_databricks_unit_tests.py
If users use 'local' mode for execution, we don't need to start a spark session. The spark session will be started if users need to create a function.
> Only create spark session in serverless mode

- connectors/spark/src/main/scala/io/unitycatalog/spark/UCSingleCatalog.scala
- Add user-facing unsupported operation exceptions for unimplemented operations in UCSingleCatalog instead of the scala default and not user-friendly 'not implemented yet' error.
- Include the catalog name in the error message when a UCSingleCatalog catalog is configured without providing a URI.
> Better error messages in UCSingleCatalog

- build.sbt
- connectors/spark/src/test/java/io/unitycatalog/spark/TableReadWriteTest.java
- docs/integrations/unity-catalog-puppygraph.md
- docs/integrations/unity-catalog-spark.md
- docs/server/auth.md
- examples/cli/src/main/java/io/unitycatalog/cli/delta/DeltaKernelUtils.java
Associated issue for this release: https://github.com/unitycatalog/unitycatalog/issues/1028
Bump spark, delta and scala version in preparation for UC 0.3.0 release against Spark/Delta 4.0
This also bumps scala version 2.13.14 to 2.13.16 and drops support for scala 2.12 isn't supported with Spark 4.0 anymore.
Testing locally:
```
JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64 build/sbt -J-Xmx2G 'testOnly'
```
Running integration tests:
```
JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64 bin/start-uc-server
JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64 build/sbt -J-Xmx2G 'integrationTests/testOnly'
```
> Bump versions: Spark 4.0.0, Delta 4.0.0, Scala 2.13.16

- build.sbt
- connectors/spark/src/test/java/io/unitycatalog/spark/TableReadWriteTest.java
Delta 4.0 is now released. Removing custom resolvers pointing to Delta 4.0 RC1 to use the central repo instead.
> Bump Delta 4.0 RC1 -> 4.0

- ai/core/pyproject.toml
Bumping the maximum version of db-connect to accommodate the new package versions that are supported on serverless: https://docs.databricks.com/aws/en/dev-tools/databricks-connect/python/install#version-support-matrix
> [AI client] Set maximum version of databricks-connect for Databricks integration 
