unitycatalog/unitycatalog

README.md

First of all, it's great to see this being open-sourced 🙌  While going over the docs, I noticed some of the syntax highlighting was missing.

docs: Add syntax highlighting

---

.github/workflows/sbt-tests.yml

Remove Failing Step in workflow

Remove Upload Dependency Graph Step

---

project/build.properties

Upgrade to sbt 1.10.0

---

.gitignore

git ignore .bsp

---

CODE_OF_CONDUCT.md
NOTICE
README.md
api/Models/CatalogInfo.md
docs/cli.md
docs/server.md
docs/tutorial.md

Fix some typos in docs

---

.gitignore
README.md
docs/tutorial.md

After running parts of the tutorial, a bunch of unintended changes appear in `git status.`
This PR adds some of those files to the .gitignore so as to reduce clutter.
This PR also fixes a couple of typos in the docs.

Update .gitignore for some of the auto generated file, and fix small typo in the docs.

---

docs/server.md

Fix a typo in server.md to fix #24

Fix typo in server.md

---

CODE_OF_CONDUCT.md

Updating the current `code of conduct` to reference and include the Linux Foundation Code of Conduct as the project is part of [LF AI & Data](https://lfaidata.foundation)

Update Code of Conduct to include LF Code of Conduct

---

docs/tutorial.md

This PR introduces typos fixes, edits, Markdown syntax changes, and rewordings based on my understanding of the Tutorial document. I tried to only make chances that enhanced the document without altering the original voice of the author(s).

addresses typos, syntax and rewordings after reading through tutorial

---

server/src/main/java/io/unitycatalog/server/persist/converters/TableInfoConverter.java

Removed duplicate (and non null checking) url set call in table converter code. Also, cleaned up some unused imports and exceptions thrown.

fix duplicate url set call in table converter

---

README.md

…rtual environment (uc_docs_venv)
Enhanced README with detailed setup instructions for creating and using a virtual environment named 'uc_docs_venv' to facilitate smoother usage.

Updated README for setting up and using a virtual env

---

server/src/main/java/io/unitycatalog/server/persist/CatalogRepository.java

use LOGGER.info to replace System.out.println for Output Log

use LOGGER.info to replace System.out.println for Output Log

---

server/src/main/java/io/unitycatalog/server/persist/FileUtils.java

fix s3 delete

---

.gitignore
tests/test_tarball_generation.py

Fix version hardcoded in tarball generation test

---

.github/workflows/sbt-tests.yml
build.sbt
project/plugins.sbt

To ensure that we don't include libraries with licenses that we don't want.

Add sbt license check

---

README.md
build.sbt
project/plugins.sbt

This configures and applies spotless for Java code. The PR is currently WIP and requires some additional documentation so that it's easier for devs to get started and include `bin/sbt spotlessApply` into their workflow when Java code formatting is off.

Configure code formatter for Java code

---

README.md

This improves the IDE section and describes how to set up the project using IntelliJ

Describe how to set up project with IntelliJ

---

build.sbt

Add netty-all explicitly as dependency in `server` project to enable proper maven artifact release.

Add netty explicitly as dependency

---

server/src/main/java/io/unitycatalog/server/persist/CatalogRepository.java
server/src/main/java/io/unitycatalog/server/persist/FunctionRepository.java
server/src/main/java/io/unitycatalog/server/persist/PropertyRepository.java
server/src/main/java/io/unitycatalog/server/persist/SchemaRepository.java
server/src/main/java/io/unitycatalog/server/persist/TableRepository.java
server/src/main/java/io/unitycatalog/server/persist/VolumeRepository.java
server/src/main/java/io/unitycatalog/server/persist/dao/CatalogInfoDAO.java
server/src/main/java/io/unitycatalog/server/persist/dao/ColumnInfoDAO.java
server/src/main/java/io/unitycatalog/server/persist/dao/FunctionInfoDAO.java
server/src/main/java/io/unitycatalog/server/persist/dao/FunctionParameterInfoDAO.java
server/src/main/java/io/unitycatalog/server/persist/dao/PropertyDAO.java
server/src/main/java/io/unitycatalog/server/persist/dao/SchemaInfoDAO.java
server/src/main/java/io/unitycatalog/server/persist/dao/TableInfoDAO.java
server/src/main/java/io/unitycatalog/server/persist/dao/VolumeInfoDAO.java
server/src/main/java/io/unitycatalog/server/persist/utils/FileUtils.java
server/src/main/java/io/unitycatalog/server/persist/utils/HibernateUtils.java
server/src/main/java/io/unitycatalog/server/persist/utils/RepositoryUtils.java
server/src/main/java/io/unitycatalog/server/persist/utils/ServerPropertiesUtils.java
server/src/main/java/io/unitycatalog/server/service/CatalogService.java
server/src/main/java/io/unitycatalog/server/service/FunctionService.java
server/src/main/java/io/unitycatalog/server/service/IcebergRestCatalogService.java
server/src/main/java/io/unitycatalog/server/service/SchemaService.java
server/src/main/java/io/unitycatalog/server/service/TableService.java
server/src/main/java/io/unitycatalog/server/service/TemporaryTableCredentialsService.java
server/src/main/java/io/unitycatalog/server/service/TemporaryVolumeCredentialsService.java
server/src/main/java/io/unitycatalog/server/service/VolumeService.java

build/sbt javafmtAll on `io.unitycatalog.server.persist` and `io.unitycatalog.server.service` package

build/sbt javafmtAll on io.unitycatalog.server.persist and io.unitycatalog.server.service package

---

server/src/main/java/io/unitycatalog/server/URLTranscoderVerticle.java
server/src/main/java/io/unitycatalog/server/UnityCatalogServer.java
server/src/main/java/io/unitycatalog/server/exception/BaseException.java
server/src/main/java/io/unitycatalog/server/exception/ErrorCode.java
server/src/main/java/io/unitycatalog/server/exception/GlobalExceptionHandler.java
server/src/main/java/io/unitycatalog/server/exception/IcebergRestExceptionHandler.java
server/src/main/java/io/unitycatalog/server/utils/ColumnUtils.java
server/src/main/java/io/unitycatalog/server/utils/Constants.java
server/src/main/java/io/unitycatalog/server/utils/JsonUtils.java
server/src/main/java/io/unitycatalog/server/utils/RESTObjectMapper.java
server/src/main/java/io/unitycatalog/server/utils/TemporaryCredentialUtils.java
server/src/main/java/io/unitycatalog/server/utils/ThrowingFunction.java
server/src/main/java/io/unitycatalog/server/utils/ValidationUtils.java
server/src/test/java/io/unitycatalog/server/sdk/volume/SdkVolumeCRUDTest.java
server/src/test/java/io/unitycatalog/server/sdk/volume/SdkVolumeOperations.java
server/src/test/java/io/unitycatalog/server/utils/FileUtilsTest.java
server/src/test/java/io/unitycatalog/server/utils/PopulateTestDatabase.java
server/src/test/java/io/unitycatalog/server/utils/SqlNameValidationTest.java
server/src/test/java/io/unitycatalog/server/utils/TestUtils.java

This formats multiple packages in the `server` module

build/sbt javafmtAll on multiple packages in server module

---

server/src/test/java/io/unitycatalog/server/base/BaseCRUDTest.java
server/src/test/java/io/unitycatalog/server/base/BaseServerTest.java
server/src/test/java/io/unitycatalog/server/base/ServerConfig.java
server/src/test/java/io/unitycatalog/server/base/catalog/BaseCatalogCRUDTest.java
server/src/test/java/io/unitycatalog/server/base/catalog/CatalogOperations.java
server/src/test/java/io/unitycatalog/server/base/function/BaseFunctionCRUDTest.java
server/src/test/java/io/unitycatalog/server/base/function/FunctionOperations.java
server/src/test/java/io/unitycatalog/server/base/schema/BaseSchemaCRUDTest.java
server/src/test/java/io/unitycatalog/server/base/schema/SchemaOperations.java
server/src/test/java/io/unitycatalog/server/base/table/BaseTableCRUDTest.java
server/src/test/java/io/unitycatalog/server/base/table/TableOperations.java
server/src/test/java/io/unitycatalog/server/base/volume/BaseVolumeCRUDTest.java
server/src/test/java/io/unitycatalog/server/base/volume/VolumeOperations.java
server/src/test/java/io/unitycatalog/server/iceberg/IcebergRestCatalogTest.java
server/src/test/java/io/unitycatalog/server/sdk/catalog/SdkCatalogCRUDTest.java
server/src/test/java/io/unitycatalog/server/sdk/catalog/SdkCatalogOperations.java
server/src/test/java/io/unitycatalog/server/sdk/function/SdkFunctionCRUDTest.java
server/src/test/java/io/unitycatalog/server/sdk/function/SdkFunctionOperations.java
server/src/test/java/io/unitycatalog/server/sdk/schema/SdkSchemaCRUDTest.java
server/src/test/java/io/unitycatalog/server/sdk/schema/SdkSchemaOperations.java
server/src/test/java/io/unitycatalog/server/sdk/tables/SdkTableCRUDTest.java
server/src/test/java/io/unitycatalog/server/sdk/tables/SdkTableOperations.java

This formats the tests in the`server` module

build/sbt javafmtAll on tests in server module

---

server/src/main/java/io/unitycatalog/server/persist/TableRepository.java

add exception output to error log for Problem localization
1. add exception output to error log for Problem localization

add exception output to error log for Problem localization

---

mkdocs.yml
requirements-docs.txt

This pr add the `materical-plausible` to mkdocs, which provides analytics and takes feedbacks from the user. 
This pr addresses #191

Adding analytics plugin for mkdocs

---

.github/CODEOWNERS

This PR is related to the issue #136
- This commit creates the CODEOWNERS file under the .github/ directory.
- Provides access to @MrPowers to the docs/ & mkdocs.yml as per the issue.

Create the CODEOWNERS file under the .github/ directory

---

README.md

Related to the PR https://github.com/unitycatalog/unitycatalog/pull/161
The `tutorial.md` file was removed but reference to it was not updated in the `README.md`

Update README.md - Fix broken reference to cli docs

---

examples/cli/src/main/java/io/unitycatalog/cli/CatalogCli.java
examples/cli/src/main/java/io/unitycatalog/cli/FunctionCli.java
examples/cli/src/main/java/io/unitycatalog/cli/SchemaCli.java
examples/cli/src/main/java/io/unitycatalog/cli/TableCli.java
examples/cli/src/main/java/io/unitycatalog/cli/UnityCatalogCli.java
examples/cli/src/main/java/io/unitycatalog/cli/VolumeCli.java
examples/cli/src/main/java/io/unitycatalog/cli/delta/ColumnVectorUtils.java
examples/cli/src/main/java/io/unitycatalog/cli/delta/DeltaKernelReadUtils.java
examples/cli/src/main/java/io/unitycatalog/cli/delta/DeltaKernelUtils.java
examples/cli/src/main/java/io/unitycatalog/cli/delta/DeltaKernelWriteUtils.java
examples/cli/src/main/java/io/unitycatalog/cli/utils/CliException.java
examples/cli/src/main/java/io/unitycatalog/cli/utils/CliParams.java
examples/cli/src/main/java/io/unitycatalog/cli/utils/CliUtils.java
examples/cli/src/main/java/io/unitycatalog/cli/utils/PythonInvoker.java

This formats the cli packages and is related to #98

build/sbt javafmtAll on cli package

---

examples/cli/src/test/java/io/unitycatalog/cli/TestUtils.java
examples/cli/src/test/java/io/unitycatalog/cli/catalog/CliCatalogCRUDTest.java
examples/cli/src/test/java/io/unitycatalog/cli/catalog/CliCatalogOperations.java
examples/cli/src/test/java/io/unitycatalog/cli/function/CliFunctionCRUDTest.java
examples/cli/src/test/java/io/unitycatalog/cli/function/CliFunctionOperations.java
examples/cli/src/test/java/io/unitycatalog/cli/schema/CliSchemaCRUDTest.java
examples/cli/src/test/java/io/unitycatalog/cli/schema/CliSchemaOperations.java
examples/cli/src/test/java/io/unitycatalog/cli/table/CliExternalTableCreationTest.java
examples/cli/src/test/java/io/unitycatalog/cli/table/CliTableCRUDTest.java
examples/cli/src/test/java/io/unitycatalog/cli/table/CliTableOperations.java
examples/cli/src/test/java/io/unitycatalog/cli/volume/CliVolumeCRUDTest.java
examples/cli/src/test/java/io/unitycatalog/cli/volume/CliVolumeOperations.java

This formats the cli tests and is related to #98

build/sbt javafmtAll on cli tests

---

server/src/main/java/io/unitycatalog/server/UnityCatalogServer.java
server/src/main/java/io/unitycatalog/server/service/TableService.java

This is a minor refactor to make TableService configuration match that of other services.
Related Issue https://github.com/unitycatalog/unitycatalog/issues/257

Refactor TableService configuration to match the common style used by other services.

---

build.sbt
connectors/spark/src/test/java/io/unitycatalog/connectors/spark/SparkIntegrationTest.java
examples/cli/src/test/java/io/unitycatalog/cli/table/CliExternalTableCreationTest.java
server/src/test/java/io/unitycatalog/server/base/BaseCRUDTest.java
server/src/test/java/io/unitycatalog/server/base/BaseServerTest.java
server/src/test/java/io/unitycatalog/server/base/catalog/BaseCatalogCRUDTest.java
server/src/test/java/io/unitycatalog/server/base/function/BaseFunctionCRUDTest.java
server/src/test/java/io/unitycatalog/server/base/schema/BaseSchemaCRUDTest.java
server/src/test/java/io/unitycatalog/server/base/table/BaseTableCRUDTest.java
server/src/test/java/io/unitycatalog/server/base/volume/BaseVolumeCRUDTest.java
server/src/test/java/io/unitycatalog/server/sdk/tables/SdkTableCRUDTest.java
server/src/test/java/io/unitycatalog/server/service/IcebergRestCatalogTest.java
server/src/test/java/io/unitycatalog/server/utils/FileUtilsTest.java
server/src/test/java/io/unitycatalog/server/utils/SqlNameValidationTest.java

Resolves #202.
* Migrate tests to JUnit 5 and remove dependencies to JUnit 4.
* Remove server configuration parametrization, as discussed in the issue.
* Use JUnit 5 annotations
* Use JUnit 5 assertions
* Bump mocking dependencies their latest versions

Migrate tests to JUnit 5

---

examples/cli/src/main/java/io/unitycatalog/cli/TableCli.java

Bugfix for "max_results" while listing assets.
Let me know if this works - I'll make similar changes to the other levels (catalog, schema, function, volume) as well.
Fixes #261

fix the list max_results bug

---

server/src/main/java/io/unitycatalog/server/persist/FunctionRepository.java
server/src/main/java/io/unitycatalog/server/persist/SchemaRepository.java
server/src/main/java/io/unitycatalog/server/persist/TableRepository.java
server/src/main/java/io/unitycatalog/server/persist/dao/CatalogInfoDAO.java
server/src/main/java/io/unitycatalog/server/persist/dao/ColumnInfoDAO.java
server/src/main/java/io/unitycatalog/server/persist/dao/FunctionInfoDAO.java
server/src/main/java/io/unitycatalog/server/persist/dao/FunctionParameterInfoDAO.java
server/src/main/java/io/unitycatalog/server/persist/dao/IdentifiableDAO.java
server/src/main/java/io/unitycatalog/server/persist/dao/SchemaInfoDAO.java
server/src/main/java/io/unitycatalog/server/persist/dao/TableInfoDAO.java
server/src/main/java/io/unitycatalog/server/persist/dao/VolumeInfoDAO.java
server/src/main/java/io/unitycatalog/server/persist/utils/PagedEntityLister.java
server/src/main/java/io/unitycatalog/server/persist/utils/PagedListingHelper.java
server/src/test/java/io/unitycatalog/server/base/table/BaseTableCRUDTest.java

Extended DAOs from a base identifiable entity to ensure we can have a common implementation for listing entities.

Create a common interface to list entities

---

docs/usage/tables/deltalake.md

Docs: Delta docs fix typos

---

build.sbt
connectors/spark/etc/conf/hibernate.properties
connectors/spark/etc/conf/server.properties
connectors/spark/src/main/scala/io/unitycatalog/connectors/spark/UCSingleCatalog.scala
connectors/spark/src/test/java/io/unitycatalog/connectors/spark/CredentialTestFileSystem.java
connectors/spark/src/test/java/io/unitycatalog/connectors/spark/FakeFileSystem.java
connectors/spark/src/test/java/io/unitycatalog/connectors/spark/SparkIntegrationTest.java

Improve the credential testing in Spark integration, to verify the credential at the low level `FileSystem`.

FileSystem level credential test

---

connectors/spark/src/main/scala/io/unitycatalog/connectors/spark/UCSingleCatalog.scala
connectors/spark/src/test/java/io/unitycatalog/connectors/spark/SparkIntegrationTest.java

Support Spark SHOW TABLES command

Support Spark SHOW TABLES command

---

connectors/spark/src/main/scala/io/unitycatalog/connectors/spark/UCSingleCatalog.scala
connectors/spark/src/test/java/io/unitycatalog/connectors/spark/SparkIntegrationTest.java

Support Spark DROP TABLE command

Support Spark DROP TABLE command

---

examples/cli/src/main/java/io/unitycatalog/cli/CatalogCli.java
examples/cli/src/main/java/io/unitycatalog/cli/SchemaCli.java
server/src/main/java/io/unitycatalog/server/persist/CatalogRepository.java
server/src/main/java/io/unitycatalog/server/persist/SchemaRepository.java
server/src/main/java/io/unitycatalog/server/service/CatalogService.java
server/src/main/java/io/unitycatalog/server/service/IcebergRestCatalogService.java

Added bugfix for `list --max_results` using PagedListingHelper as recommended [here](https://github.com/unitycatalog/unitycatalog/pull/271#discussion_r1693351596).
cc: @vikrantpuppala

Fix list max results

---

server/src/main/java/io/unitycatalog/server/persist/TableRepository.java

add failure message for table creation

---

docs/usage/functions.md

Fix a possible mistake:
The `DATA_TYPE` field tells us that the inputs should be of `INT` data type.
->
The `DATA_TYPE` field tells us that the output should be of `INT` data type.

Fix a possible mistake in functions.md

---

connectors/spark/src/main/scala/io/unitycatalog/connectors/spark/UCSingleCatalog.scala
connectors/spark/src/test/java/io/unitycatalog/connectors/spark/SparkIntegrationTest.java

Add `SupportsNamespaces` in UCSingleCatalog class and implemented `listNamespaces` and `loadNamespaceMetadata`, which support `SHOW NAMESPACES` and `DESC NAMESPACE` command.

Support SHOW/DESC NAMESPACE

---

connectors/spark/src/test/java/io/unitycatalog/connectors/spark/SparkIntegrationTest.java

Test UPDATE/MERGE/DELETE Commands

[SPARK] Test UPDATE/MERGE/DELETE Commands

---

connectors/spark/src/main/scala/io/unitycatalog/connectors/spark/UCSingleCatalog.scala
connectors/spark/src/test/java/io/unitycatalog/connectors/spark/SparkIntegrationTest.java

Test Create/Drop Database Command for Spark.

[SPARK] Test Create/Drop Database Command

---

README.md
docker/README.md

The following simple `readme.md` changes are included in this PR
* For `README.md`, clarifying how to exit DuckDB shell
* For `docker\README.md`, clarifying prerequesite of `jq`
Key changes are text related for readability

Simple readme.md updates

---

connectors/spark/src/main/scala/io/unitycatalog/connectors/spark/UCSingleCatalog.scala
connectors/spark/src/test/java/io/unitycatalog/connectors/spark/SparkIntegrationTest.java

Support Spark `CREATE EXTERNAL TABLE LOCATION` command

[SPARK] CREATE EXTERNAL TABLE LOCATION

---

connectors/spark/src/main/scala/io/unitycatalog/connectors/spark/UCSingleCatalog.scala
connectors/spark/src/test/java/io/unitycatalog/connectors/spark/TableReadWriteTest.java

Add CREATE TABLE tests for Delta. It's ignored for now as we need to wait for the Delta fix: https://github.com/delta-io/delta/pull/3497

Add tests for creating external delta table

---

docs/integrations/unity-catalog-xtable.md

Resolves this issue - https://github.com/unitycatalog/unitycatalog/issues/160
- Documentation change only

docs: Apache XTable Guide for Unity Catalog

---

build.sbt

spark shaded server and managed client dependency

---

README.md

Make README more legible and correct.

Root README clarity and grammar edits

---

connectors/spark/src/test/java/io/unitycatalog/connectors/spark/CredentialTestFileSystem.java
connectors/spark/src/test/java/io/unitycatalog/connectors/spark/SchemaOperationsTest.java
connectors/spark/src/test/java/io/unitycatalog/connectors/spark/TableReadWriteTest.java

[SPARK] Format code

---

docs/usage/functions.md

docs: fix typo

---

api/Apis/ModelsApi.md
api/Models/CreateModelVersion.md
api/Models/CreateRegisteredModel.md
api/Models/ListModelVersionsResponse.md
api/Models/ListRegisteredModelsResponse.md
api/Models/ModelVersionInfo.md
api/Models/ModelVersionStatus.md
api/Models/RegisteredModelInfo.md

Added the ModelsApi.md file along with dependant files.

Added the ModelsApi.md file and downstream dependency files.

---

.gitignore

- Signing keys and access tokens added to `.gitignore` which were introduced in #277.
- Also added the `h2db.trace.db` to `.gitignore`.

Add signing keys, access tokens and h2db trace file to .gitignore.

---

api/all.yaml
examples/cli/src/main/java/io/unitycatalog/cli/ModelCli.java
examples/cli/src/main/java/io/unitycatalog/cli/utils/CliUtils.java
examples/cli/src/test/java/io/unitycatalog/cli/model/CliModelOperations.java
server/src/main/java/io/unitycatalog/server/persist/ModelRepository.java
server/src/main/java/io/unitycatalog/server/persist/utils/RepositoryUtils.java
server/src/main/java/io/unitycatalog/server/service/ModelService.java
server/src/test/java/io/unitycatalog/server/base/model/BaseModelCRUDTest.java
server/src/test/java/io/unitycatalog/server/base/model/ModelOperations.java
server/src/test/java/io/unitycatalog/server/sdk/models/SdkModelOperations.java
server/src/test/java/io/unitycatalog/server/utils/TestUtils.java

Fixed the ListRegisteredModels endpoint to allow for catalog_name and schema_name to be optional, and enforce that either both are set or none are.  When neither are set, we return all visible registered models.

Updated ListRegisteredModels to comport with DB UC

---

docs/quickstart.md

Improve the quickstart.md with UC CLI cmds.
- Adding format to the UC CLI cmds 
- Adding table cleanup.

Docs: Improve the quickstart.md with UC CLI cmds.

---

server/src/main/java/io/unitycatalog/server/persist/utils/UriUtils.java

Javafmt fix for UriUtils

---

api/Apis/ModelVersionsApi.md
api/Apis/RegisteredModelsApi.md
api/Apis/TablesApi.md
api/Apis/TemporaryModelVersionCredentialsApi.md
api/Models/AzureUserDelegationSAS.md
api/Models/CreateModelVersion.md
api/Models/CreateTable.md
api/Models/FinalizeModelVersion.md
api/Models/GcpOauthToken.md
api/Models/GenerateTemporaryModelVersionCredentials.md
api/Models/GenerateTemporaryModelVersionCredentialsResponse.md
api/Models/GenerateTemporaryVolumeCredentialResponse.md
api/Models/ListModelVersionsResponse.md
api/Models/ListRegisteredModelsResponse.md
api/Models/ModelVersionInfo.md
api/Models/ModelVersionOperation.md
api/Models/RegisteredModelInfo.md
api/Models/UpdateModelVersion.md
api/Models/UpdateRegisteredModel.md
api/README.md

The API yaml file was updated but the docs weren't, just bringing them back in sync

update docs by running `sbt generate`

---

connectors/spark/src/test/java/io/unitycatalog/spark/TableReadWriteTest.java

Format the test file using javafmtAll

Run `javafmtAll` on main repo

---

server/src/main/java/io/unitycatalog/server/persist/CatalogRepository.java
server/src/main/java/io/unitycatalog/server/persist/FunctionRepository.java
server/src/main/java/io/unitycatalog/server/persist/ModelRepository.java
server/src/main/java/io/unitycatalog/server/persist/SchemaRepository.java
server/src/main/java/io/unitycatalog/server/persist/TableRepository.java
server/src/main/java/io/unitycatalog/server/persist/VolumeRepository.java
server/src/main/java/io/unitycatalog/server/persist/dao/ModelVersionInfoDAO.java
server/src/main/java/io/unitycatalog/server/persist/dao/RegisteredModelInfoDAO.java
server/src/main/java/io/unitycatalog/server/persist/dao/VolumeInfoDAO.java
server/src/main/java/io/unitycatalog/server/utils/IdentityUtils.java

Enable identity tracking for all create and update paths for securables in UC OSS

Enable identity logging on create/update paths

---

build.sbt

Specify release settings for spark connector

Specify release settings for spark connector

---

connectors/spark/src/test/java/io/unitycatalog/spark/TableReadWriteTest.java

This PR is to test parquet table creation by create table or create table select as

[SPARK] Test parquet table creation by Spark 3.5.3

---

build.sbt

We don't want the dependency resolvers to pull in an extra version of spark

Mark spark-sql dependency as Provided

---

ui/src/hooks/catalog.tsx
ui/src/hooks/functions.tsx
ui/src/hooks/models.tsx
ui/src/hooks/schemas.tsx
ui/src/hooks/tables.tsx
ui/src/hooks/volumes.tsx
ui/src/pages/ModelVersionDetails.tsx

- [ x] A description of the changes is added to the description of this PR.
Add the `owner` `created_by` and `updated_by` fields to all other entities (models already has them from previous PR). If the fields are populated, they will display in the details sidebar of each entity. 
Also, removing non-functional "add/edit description" button from version details page (missed this straggler in previous PR).

add new acl fields to all entities

---

build.sbt

Updated Delta 3.2.1 to new RC

---

examples/cli/src/main/java/io/unitycatalog/cli/utils/Oauth2CliExchange.java

Simple wording change for CLI login process.

Change wording on successful identity provider validation.

---

ui/README.md

fix ui readme image link

---

build.sbt

Remove delta 3.2.1 prerelease resolver, official release is out

---

server/src/main/java/io/unitycatalog/server/auth/decorator/UnityAccessDecorator.java

Fix javadoc generation issue
e.g. `unknown tag: AuthorizeKey`

Fix javadoc generation issue

---

docs/usage/cli.md
docs/usage/ui.md

- Fixed image loc in UI doc
- Added managing users to CLI doc

Update docs to include CLI managing users

---

api/Apis/GrantsApi.md
api/Models/PermissionsChange.md
api/Models/PermissionsList.md
api/Models/PrincipalType.md
api/Models/Privilege.md
api/Models/PrivilegeAssignment.md
api/Models/SecurableType.md
api/Models/UpdatePermissions.md
api/README.md

Only run `build/sbt generate` to update the docs without any other changes

Update docs by running `build/sbt generate`

---

ui/src/components/modals/DeleteModelModal.tsx
ui/src/components/models/ModelActionsDropdown.tsx
ui/src/hooks/models.tsx
ui/src/pages/ModelDetails.tsx

- [ X] A description of the changes is added to the description of this PR.
Users can delete models from the UI.

[UI] Feat/delete model

---

api/Models/CreateModelVersion.md
api/all.yaml
examples/cli/src/main/java/io/unitycatalog/cli/utils/CliUtils.java
examples/cli/src/test/java/io/unitycatalog/cli/access/CliAccessControlModelCrudTest.java
examples/cli/src/test/java/io/unitycatalog/cli/model/CliModelOperations.java
server/src/main/java/io/unitycatalog/server/service/ModelService.java
server/src/test/java/io/unitycatalog/server/base/model/BaseModelCRUDTest.java

Source was erroneously left off of the required list for CreateModelVersion when checked in.  In this PR we:
- Add source as required at at the API
- Add service handler checks for source existence
- Add an explicit test in the unit test to validate that source must be filled in.

Make source required

---

api/Models/UpdateModelVersion.md
api/Models/UpdateRegisteredModel.md
api/all.yaml
examples/cli/src/main/java/io/unitycatalog/cli/ModelCli.java
examples/cli/src/main/java/io/unitycatalog/cli/ModelVersionCli.java
examples/cli/src/test/java/io/unitycatalog/cli/model/CliModelOperations.java
server/src/main/java/io/unitycatalog/server/persist/ModelRepository.java
server/src/main/java/io/unitycatalog/server/service/ModelService.java
server/src/test/java/io/unitycatalog/server/base/model/BaseModelCRUDTest.java

Fix a bug where the path variables for UpdateModelVersion and UpdateRegisteredModel were being ignored in favor of the incorrectly added variables in the request object.
- Request object has been fixed
- Path variables are passed in correctly for both handlers and used
- All existing code that relied on extraneous fields in generated code has been fixed
- All tests continue to pass

Fix UpdateRegisteredModel and UpdateModelVersion to honor path variables

---

ui/src/components/modals/EditVersionDescriptionModal.tsx
ui/src/hooks/models.tsx
ui/src/pages/ModelVersionDetails.tsx

User can update model version description via the UI.

[UI] Feat/update model version description

---

ui/src/components/modals/EditModelDescriptionModal.tsx
ui/src/hooks/models.tsx
ui/src/pages/ModelDetails.tsx

User can add/edit model description via the UI.

[UI] Edit registered model description

---

server/src/main/java/io/unitycatalog/server/UnityCatalogServer.java
server/src/main/java/io/unitycatalog/server/auth/UnityCatalogAuthorizer.java
server/src/main/java/io/unitycatalog/server/service/PermissionService.java

A `branch-0.2` version of ff45a52e26c0bfb7f467f39edf8b23d59c0db454
/cc @creechy

[MINOR] Remove duplicate + no publics in interface

---

unitycatalog-ai/src/ucai/core/utils/function_processing_utils.py
unitycatalog-ai/src/ucai/core/utils/pydantic_utils.py
unitycatalog-ai/src/ucai/core/utils/type_utils.py
unitycatalog-ai/src/ucai/core/utils/validation_utils.py

FR: https://github.com/unitycatalog/unitycatalog/issues/525
Add some utility functions for validating params in preparation for databricks client integration.

ucai-core databricks utils

---

unitycatalog-ai/README.md
unitycatalog-ai/pyproject.toml
unitycatalog-ai/src/ucai/test_utils/client_utils.py
unitycatalog-ai/src/ucai/test_utils/function_utils.py
unitycatalog-ai/tests/core/test_client.py
unitycatalog-ai/tests/core/test_utils.py

Add tests for core UC function client.

Core tests

---

unitycatalog-ai/README.md
unitycatalog-ai/src/ucai/core/databricks.py
unitycatalog-ai/src/ucai/core/envs/databricks_env_vars.py
unitycatalog-ai/tests/core/test_databricks_client.py

Databricks function client support, implement all methods in the BaseFunctionClient and added unit tests + integration tests.
This PR is large mostly because of the test suite :)

databricks function client support

---

server/src/test/java/io/unitycatalog/server/utils/TestUtils.java

Remove unused method from TestUtils

Remove unused method from TestUtils

---

connectors/spark/src/test/java/io/unitycatalog/spark/SchemaOperationsTest.java
connectors/spark/src/test/java/io/unitycatalog/spark/TableReadWriteTest.java
examples/cli/src/test/java/io/unitycatalog/cli/access/CliAccessControlBaseCrudTest.java
examples/cli/src/test/java/io/unitycatalog/cli/auth/CliAuthCrudTest.java
server/src/test/java/io/unitycatalog/server/auth/JCasbinAuthorizerTest.java

Migrate JUnit assertions to AssertJ.

Migrate JUnit assertions to AssertJ

---

examples/cli/src/test/java/io/unitycatalog/cli/table/CliExternalTableCreationTest.java

Use FileUtils.deleteDirectory

---

server/src/main/java/io/unitycatalog/server/URLTranscoderVerticle.java
server/src/main/java/io/unitycatalog/server/persist/ModelRepository.java
server/src/main/java/io/unitycatalog/server/persist/TableRepository.java
server/src/main/java/io/unitycatalog/server/persist/utils/FileUtils.java
server/src/main/java/io/unitycatalog/server/persist/utils/UriUtils.java

Replace string concat with logger template

Replace string concat with logger template

---

server/src/main/java/io/unitycatalog/server/security/SecurityContext.java

Fix logger class in SecurityContext

Fix logger class in SecurityContext

---

server/src/test/java/io/unitycatalog/server/base/credentials/BaseTemporaryModelVersionCredentialsTest.java

Replace try-catch with assertThatThrownBy

Replace try-catch with assertThatThrownBy

---

ui/src/components/modals/CreateModelModal.tsx
ui/src/components/schemas/SchemaActionDropdown.tsx
ui/src/hooks/models.tsx

create registered model from the ui
(cherry picked from commit c53ce3391d16864b0e50be895379a4cec96e1e8c)

Feat/create model (#576)

---

unitycatalog-ai/src/ucai/core/utils/callable_utils.py
unitycatalog-ai/src/ucai/core/utils/docstring_utils.py
unitycatalog-ai/tests/core/test_callable_utils.py
unitycatalog-ai/tests/core/test_docstring_utils.py

This PR includes enhancements for handling non-standard Google-style docstrings, common typos, and the handling of missing descriptions within argument key entries within a docstring. 
Additionally, added comprehensive test coverage for the validation of parsing functionality and the extraction of both type declarations within callable signatures and the descriptions within python docstrings.
Documentation guide regarding the features contained within this PR will be filed in a followup.

[UCAI] Add enhancements to docstring parsing for function creation from python callable

---

docs/integrations/unity-catalog-celerdata.md

Add CelerData Integration quickstart doc

Add CelerData Integration

---

docs/usage/cli.md

Add docs on how to use the metastore cli commands

[0.3] Add metastore cli doc

---

server/src/main/java/io/unitycatalog/server/persist/ModelRepository.java
server/src/main/java/io/unitycatalog/server/persist/UserRepository.java
server/src/main/java/io/unitycatalog/server/persist/utils/UriUtils.java

Remove unused method

---

README.md
docs/README.md
mkdocs.yml

Adding the skeleton of a dedicated README in the `docs` directory. The README is excluded from `mkdocs.yml`. Final content of the README will be added in #550.
Resolves #628

Move documentation README to docs

---

mkdocs.yml

Removes the additional whitespaces at the line end in `mkdocs.yml`.
Resolves #672

Remove additional whitespace at line end from MkDocs configuration

---

docs/server/auth.md
docs/server/configuration.md
docs/server/google-auth.md

Update the formatting of the `server` documentation pages by using markdownlint. User-facing changes have been kept minimal.
Resolves #668

Format server documentation pages via markdownlint

---

mkdocs.yml

Added the CelerData Integration documentation to the navigation in MkDocs to be displayed in the published documentation version.
Resolves #670

Add CelerData Integration documentation to navigation

---

.pre-commit-config.yaml
requirements-docs.txt

Updating the dependencies declared in `requirements-docs.txt` to their latest version.
Resolves #685

Update dependencies for docs to latest version

---

docs/usage/cli.md

fix doc, user command is missing from creating user example

Update cli.md, user command missing from create user example

---

ai/core/src/unitycatalog/ai/core/utils/validation_utils.py

Fix failure found by https://github.com/databricks-eng/ai-oss-integration-tests-runner/actions/runs/11736443394/job/32695707613
Validated this PR by https://github.com/databricks-eng/ai-oss-integration-tests-runner/actions/runs/11737652994/job/32698804621

Fix check_function_info

---

ai/integrations/crewai/tests/test_toolkit.py

Fix failing crewai tests, validated in https://github.com/databricks-eng/ai-oss-integration-tests-runner/actions/runs/11928462059

Fix crewai test

---

etc/conf/server.properties
server/src/main/java/io/unitycatalog/server/service/AuthDecorator.java
server/src/main/java/io/unitycatalog/server/service/AuthService.java
server/src/test/java/io/unitycatalog/server/service/AuthServiceTest.java
ui/src/App.tsx
ui/src/context/auth-context.tsx
ui/src/hooks/user.tsx

backporting all the http cookie PR's into 0.2 branch

Backport http cookie prs

---

server/src/main/java/io/unitycatalog/server/UnityCatalogServer.java

Fix server default constructor

Fix server default constructor

---

.gitignore
build.sbt
server/src/main/java/io/unitycatalog/server/UnityCatalogServer.java

Backporting PR #747 and #745 for 0.2.1 release

[BACKPORT] Create single maven artifact for server

---

ai/core/README.md

Updates the AI core library README with guidance on using the UC OSS server as a backend for the functions APIs.

Add entries for guidance on UC OSS to the AI core README

---

api/control.yaml
server/src/main/java/io/unitycatalog/server/UnityCatalogServer.java
server/src/main/java/io/unitycatalog/server/service/Scim2SelfService.java
server/src/main/java/io/unitycatalog/server/service/Scim2UserService.java
server/src/main/java/io/unitycatalog/server/utils/Scim2Utils.java
ui/src/hooks/user.tsx

This replaces the `/Users/self` endpoint with a SCIM 2.0 compliant `/Me` endpoint.

Create a SCIM 2.0 /Me endpoint and decommission /Users/self.

---

examples/cli/src/main/java/io/unitycatalog/cli/utils/Oauth2CliExchange.java
server/src/main/java/io/unitycatalog/server/service/CatalogService.java
server/src/main/java/io/unitycatalog/server/service/PermissionService.java
server/src/main/java/io/unitycatalog/server/service/TemporaryModelVersionCredentialsService.java
server/src/test/java/io/unitycatalog/server/service/AuthServiceTest.java

Minor auth-related changes:
1. New Fields.CODE
2. Use Fields constants whenever possible
3. Formatting

[MINOR] New Fields.CODE and Formatting

---

.github/workflows/ucai-integration-tests-oss.yml
.github/workflows/ucai-integration-tests.yml
ai/core/src/unitycatalog/ai/test_utils/function_utils.py
ai/core/src/unitycatalog/ai/test_utils/function_utils_oss.py
ai/integrations/openai/tests/test_openai_toolkit_oss.py

Adds integration tests for the unitycatalog-openai integration to validate functionality with the OSS Unity Catalog server

Add OSS integration tests for unitycatalog-openai

---

ai/core/src/unitycatalog/ai/core/base.py
ai/core/src/unitycatalog/ai/core/databricks.py
ai/core/src/unitycatalog/ai/core/utils/function_processing_utils.py
ai/integrations/langchain/src/unitycatalog/ai/langchain/toolkit.py

Add `include_browse` option in `list_functions` for databricks client (OSS client doesn't have this option); Update `process_function_names` to set `include_browse=False` if the client accepts such kwarg.

Fix list functions

---

Dockerfile

Modified line 2 of the server's Dockerfile, fixing the HOME variable in the file.
This PR fixes issue #755.

fix : HOME variable in dockerfile of uc-server

---

ai/integrations/crewai/src/unitycatalog/ai/crewai/toolkit.py

Handle the BaseTool namespace migration made in https://github.com/crewAIInc/crewAI-tools/commit/68661c8d998360a53329795ffae1dcca5048fe88 to ensure that we're compatible with the breaking change.

Fix breaking change made in crewai-tools

---

.github/workflows/mlflow-integration-tests.yml
tests/test_mlflow_integration.py

Added a github workflow that starts all necessary servers and tests the mlflow integration against the existing PR.

Add mlflow integration test as github workflow

---

.github/CODEOWNERS

AI docs codeowner update

---

ai/CHANGELOG.md
docs/ai/client.md
docs/ai/integrations/anthropic.md
docs/ai/integrations/autogen.md
docs/ai/integrations/crewai.md
docs/ai/integrations/langchain.md
docs/ai/integrations/llamaindex.md
docs/ai/integrations/openai.md
docs/ai/quickstart.md

Adds a distinct changelog tracker for the ai/ components in UnityCatalog and fixes some naming / header issues in the docs for the AI components

Add changelog for 0.1.0 release of unitycatalog-ai and update docs entries

---

ai/integrations/autogen/README.md
ai/integrations/autogen/autogen_example.ipynb

Fix an invalid install of autogen and update the documentation with clarification regarding the correct repo / library due to forks that have been created and pushed to PyPI

Add clarifications to the AutoGen package documentation

---

server/src/main/java/io/unitycatalog/server/UnityCatalogServer.java
server/src/main/java/io/unitycatalog/server/service/credential/CredentialOperations.java
server/src/main/java/io/unitycatalog/server/service/credential/aws/AwsCredentialVendor.java
server/src/main/java/io/unitycatalog/server/service/credential/azure/AzureCredentialVendor.java
server/src/main/java/io/unitycatalog/server/service/credential/gcp/GcpCredentialVendor.java
server/src/main/java/io/unitycatalog/server/service/iceberg/FileIOFactory.java
server/src/main/java/io/unitycatalog/server/service/iceberg/TableConfigService.java
server/src/main/java/io/unitycatalog/server/utils/ServerProperties.java
server/src/test/java/io/unitycatalog/server/base/BaseServerTest.java
server/src/test/java/io/unitycatalog/server/service/credential/CredentialOperationsTest.java

This PR adds code improvements to the server namely:
1. Allow injection of cloud credential vendor classes
2. Builder pattern to initialize server
3. Break down server init to smaller functions
4. Reduce staticness associated with serverProperties (future PR to remove this completely)

Improvements to the server code

---

ai/core/src/unitycatalog/ai/core/databricks.py
ai/core/tests/core/databricks/function_definitions.py
ai/core/tests/core/databricks/test_databricks_integration_tests.py
ai/integrations/anthropic/tests/test_anthropic_utils.py
ai/integrations/autogen/tests/test_autogen_toolkit.py
ai/integrations/crewai/tests/test_crewai_toolkit.py
ai/integrations/langchain/tests/test_langchain_toolkit.py
ai/integrations/llama_index/tests/test_llama_index_toolkit.py
ai/integrations/openai/tests/test_openai_toolkit.py
ai/integrations/openai/tests/test_openai_utils.py

Fix integration tests

---

.gitignore
ai/core/src/unitycatalog/ai/core/utils/function_processing_utils.py
ai/integrations/anthropic/src/unitycatalog/ai/anthropic/toolkit.py
ai/integrations/anthropic/tests/test_anthropic_toolkit.py
ai/integrations/anthropic/tests/test_anthropic_toolkit_oss.py
ai/integrations/autogen/src/unitycatalog/ai/autogen/toolkit.py
ai/integrations/crewai/src/unitycatalog/ai/crewai/toolkit.py
ai/integrations/langchain/src/unitycatalog/ai/langchain/toolkit.py
ai/integrations/langchain/tests/test_langchain_toolkit.py
ai/integrations/llama_index/src/unitycatalog/ai/llama_index/toolkit.py
ai/integrations/openai/src/unitycatalog/ai/openai/toolkit.py
ai/integrations/openai/tests/test_openai_toolkit.py
ai/integrations/openai/tests/test_openai_toolkit_oss.py

Databricks's List API doesn't include input_params in the result, so when the tools are used in agents input parameters are missing from the function info. This PR fixes this issue by always use GET API to fetch full function info.
Also added integration tests

Fix toolkit

---

docs/quickstart.md

PR Checklist
Description of changes
In this PR, I found that 'UC' was used in several places, so I changed them to 'Unity Catalog' for better readability and removed unnecessary spaces before folder names. No users will be impacted by these changes.

Made some basic changes in the QuickStart.md file Docs Updated

---

docs/ai/integrations/gemini.md
docs/ai/integrations/index.md
docs/ai/usage.md

Adds docs for the Gemini integration in unitycatalog-gemini

Add documentation for the Gemini integration

---

ai/integrations/litellm/README.md
docs/ai/integrations/litellm.md
docs/ai/usage.md

Adds documentation for the LiteLLM integration.

Add litellm docs

---

ai/core/pyproject.toml
ai/integrations/autogen/pyproject.toml

Update versions for 0.2.0 unitycatalog-ai release

---

ai/CHANGELOG.md

Add release notes for Unity Catalog AI 0.2.0

---

ai/integrations/langchain/pyproject.toml
docs/ai/integrations/gemini.md
docs/ai/integrations/litellm.md
mkdocs.yml

Doc sidebar fix and version bump for unitycatalog-langchain release

---

ai/integrations/llama_index/README.md
docs/ai/integrations/llamaindex.md

Fix a misleading callable entry for LlamaIndex within the docs

---

ai/integrations/gemini/README.md

Fix the path in Gemini README.md

Update README.md - fix path

---

.github/workflows/docker-build.yml

Duplicate of #698
Pushed from non-fork to allow access to Docker secrets, uploaded to this repository.

[BUILD] Push official docker image on tagged release

---

ai/core/README.md
ai/core/pyproject.toml
ai/core/src/unitycatalog/ai/core/databricks.py
docs/ai/client.md

Unpins databricks-connect to use a minimum version specifier. Manual testing in DBR has confirmed that later versions work just fine with higher versions.

unpin databricks-connect

---

ai/integrations/crewai/pyproject.toml
ai/integrations/crewai/src/unitycatalog/ai/crewai/version.py

Increment the crewai integration version for a patch release

---

ai/integrations/langchain/src/unitycatalog/ai/langchain/toolkit.py

Silences a known noisy warning when using the LangChain toolkit integration.

silence langchain warning

---

ui/src/App.tsx

- Updated `App` to provide `AuthProvider` only when authentication is enabled.
Will close #766 .

[UI] Update App to provide AuthProvider only when auth is enabled

---

ai/CHANGELOG.md
ai/core/pyproject.toml
ai/integrations/anthropic/pyproject.toml
ai/integrations/autogen/pyproject.toml
ai/integrations/crewai/pyproject.toml
ai/integrations/gemini/pyproject.toml
ai/integrations/langchain/pyproject.toml
ai/integrations/litellm/pyproject.toml
ai/integrations/llama_index/pyproject.toml
ai/integrations/openai/pyproject.toml

Release notes and version update for unitycatalog-ai 0.3.0

---

.github/workflows/docker-build.yml

Run docker workflow only on tagged releases instead of all PRs

Run docker workflow only on tagged releases

---

build.sbt
server/src/main/java/io/unitycatalog/server/service/IcebergRestCatalogService.java
server/src/test/java/io/unitycatalog/server/service/IcebergRestCatalogTest.java

Upgrade Iceberg to [1.8.1](https://github.com/apache/iceberg/releases/tag/apache-iceberg-1.8.1).

Upgrade Iceberg to 1.8.1

---

ai/core/src/unitycatalog/ai/core/base.py
ai/core/src/unitycatalog/ai/core/client.py
ai/core/tests/core/oss/test_oss_client.py
ai/integrations/anthropic/tests/test_anthropic_toolkit.py
ai/integrations/anthropic/tests/test_anthropic_toolkit_oss.py

Removes the string wrapping that we've been doing for the function clients to return the native types.

Remove the string wrapping from the function clients return

---

docs/integrations/unity-catalog-kuzu.md

Resolves #971
Fix markdown-lint issues on the Kuzu integration documentation page.

Update Kuzu Integration documentation to align formatting with other pages

---

.github/workflows/docker-build.yml

Add CI workflow to regularly build and push unstable server images from fresh `main` branch commits

[CI] Add unstable docker build workflow for server

---

docs/usage/api/catalogs.md
docs/usage/api/functions.md
docs/usage/api/index.md
docs/usage/api/models.md
docs/usage/api/schemas.md
docs/usage/api/tables.md
docs/usage/api/volumes.md
mkdocs.yml

This PR adds a dedicated section in the docs to explain and demonstrate using Unity Catalog REST API.
Signed-off-by: Avril Aysha <68642378+avriiil@users.noreply.github.com>

[DOCS] Add REST API section

---

docs/integrations/unity-catalog-daft.md

pip install getdaft -> pip install daft

docs: update to `pip install daft`

---

.github/workflows/docker-build.yml

Add manual trigger for docker push workflow

---

ai/core/src/unitycatalog/ai/core/client.py
ai/core/tests/core/oss/test_oss_client.py

get_function_async returns None if no function existing, fix the corresponding error in create_function_async

Fix oss client create function

---

ai/integrations/langchain/tests/test_langchain_toolkit.py
ai/integrations/langchain/tests/test_langchain_toolkit_oss.py

Latest langgraph doesn't accept `state_modifier` in create_react_agent

Fix langgraph test

---

ui/Dockerfile

Workaround to make ui docker buildable in Github Actions

---

.pre-commit-config.yaml
helm/.helmignore
helm/Chart.yaml
helm/README.md
helm/README.md.gotmpl
helm/generate-docs.sh
helm/templates/_helpers.tpl
helm/templates/httpRoute.yaml
helm/templates/ingress.yaml
helm/templates/server/_config.tpl
helm/templates/server/configmap.yaml
helm/templates/server/create-users-job.yaml
helm/templates/server/db-pvc.yaml
helm/templates/server/deployment.yaml
helm/templates/server/keypair-secret.yaml
helm/templates/server/service.yaml
helm/templates/serviceaccount.yaml
helm/templates/ui/deployment.yaml
helm/templates/ui/service.yaml
helm/values.httproute.yaml
helm/values.yaml

Bringing helm chart from - https://github.com/sdwbgn/unitycatalog-helm
Features:
- Deploys UC Server and UI
- UC Configuration from helm values
- OAuth
- Data sources configuration (S3, GCS, ADLS) with secret management
- Persistence of data in PVCs
Relates: https://github.com/unitycatalog/unitycatalog/issues/433

Add helm chart for unitycatalog

---

ai/integrations/gemini/tests/test_gemini_toolkit.py

This small PR fixes the duplicate `test_toolkit_creation_errors` test in `http://test_gemini_toolkit.py`.

Fix Gemini toolkit test

---

build.sbt

Update Iceberg to 1.9.1 https://github.com/apache/iceberg/releases/tag/apache-iceberg-1.9.1

Update Iceberg to 1.9.1

---

build.sbt

Update Iceberg to 1.9.2 https://iceberg.apache.org/releases/#192-release

Update Iceberg to 1.9.2
